### ISSUE TITLE
How to ignore code suggestions?

### ISSUE THREAD

**Issue by failable** [fredcamps/lsp-jedi#6]
Hi, 

It seems that I can always get code suggestions wherever the cursor is

<img width="263" alt="Screen Shot 2020-09-08 at 2 03 52 PM" src="https://user-images.githubusercontent.com/5475262/92438893-533fa300-f1dc-11ea-8447-0154ad73ec95.png">

Can I ignore these code actions while keeping warnings and errors from linters? Thanks!

**Comment by fredcamps** [comment]
Hi @isolet 

You can change custom variables like
```lisp
(setq lsp-jedi-trace-server "off")
(setq lsp-jedi-diagnostics-enable nil)
```

I would like to know if it works, thanks for using lsp-jedi.

**Comment by failable** [comment]
Hi, thanks for the hints. But it doesn't work...The code action are still there. I confirmed it by restarting a new Emacs session and LSP process. 
<img width="662" alt="Screen Shot 2020-09-17 at 11 40 20 AM" src="https://user-images.githubusercontent.com/5475262/93417417-b2876c80-f8da-11ea-97ac-af97753d6059.png">

**Comment by fredcamps** [comment]
@isolet that's wierd, I can't  reproduce this

**Comment by bbenne10** [comment]
I'm having the same problem here. I've set both variables and restarted the workspace server and no dice.

Is it possible it is a server version thing? I'm using 0.19.4 (latest as of this writing). @fredcamps: Are you on an older revision?

**Comment by fredcamps** [comment]
@bbenne10 I'm using 0.19.3 right now

**Comment by failable** [comment]
Both versions have the same issue for me..

**Comment by bbenne10** [comment]
I wonder then if there's so supporting package or configuration that leads
to this behavior.

I'll put a few minutes in today to seeing if I can isolate it to a minimal
reproducible case

>

**Comment by bbenne10** [comment]
Okay - This is how I was able to reproduce in a simple setup.

pip packages
```
❯ pip freeze                                                                                                                                                               ~/test_lsp_jedi
click==7.1.2
jedi==0.17.2
jedi-language-server==0.19.4
parso==0.7.1
pygls==0.9.1
```

emacs configuration: you can simplify this further, but this is the minimal I was using as I use direnv to manage my venvs. Feel free to remove it if you're not using direnv.

```elisp
;; This just sets up straight - feel free to nuke if you want vanilla use-package or package.el or whatever
(defvar bootstrap-version)
(let ((bootstrap-file  (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
       (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
      (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"     'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)

  ;; and setting up direnv because I manage all my venvs with it
  (use-package direnv 
    :config (direnv-mode))

  ;; and now onto the 100% relevant stuff
  (use-package lsp-ui)
  (use-package lsp-mode
    :hook ((python-mode . lsp))
    :commands lsp)
  (use-package lsp-jedi)
```

and finally the file (which I had in `main.py`, but the name shouldn't matter)

```python3
def add(x, y):
  return x + y

if __name__ == "__main__":
  add(3, 4)
```

With this, I see the attached.
![Screen Shot 2020-10-14 at 9 16 38 AM](https://user-images.githubusercontent.com/687376/95995086-0b292700-0dff-11eb-881a-7288bacdf186.png)

**Comment by fredcamps** [comment]
@bbenne10 I'm using lsp-jedi without lsp-ui and flycheck-lsp, for diagnostics I'm just using flycheck, that's reason why I can't reproduce this, Did you try to disable flycheck-lsp and use flycheck-pylint or flycheck-flake8 instead?

**Comment by bbenne10** [comment]
I have not tried that. I can certainly do so, but that seems to defeat the purpose for me. Using the language server for the linting is part of the reason I use lsp in the first place (unifying everything rather than splintering out again like we've done in the past). 

If linting is explicitly not supported (or - almost worse - simply implicitly not supported and fundamentally untested) with this package, I think that that is worth at least a note in the readme. 

I won't have time to get around to testing that configuration out until at least tomorrow, but I'll get there before long :)

**Comment by wyuenho** [comment]
The answer is to disable `lsp-ui-sideline-show-code-actions` if you are using lsp-ui, or turn off `lsp-auto-execute-action` and `lsp-modeline-code-actions-enable` in regular `lsp-mode`.

**Comment by bbenne10** [comment]
"Disable these things" is a perfectly fine answer, but maybe tell users that these things aren't supported.
Without that last step, it is a non-answer and I am sure you'll see this question again or at least people will find this issue and realize the error, which you're now putting on the user rather than on the project (which I believe to be a mistake, but you all may disagree, and that's fine - do your thing)

I dropped the ball on testing and reporting back on this (and for that I greatly apologize) but my interest in the project waned when its goals did not meet my own. Keep closed if you want, but some real documentation about this would really help.

**Comment by wyuenho** [comment]
Code action will work once #9 is merged. I wasn't answering to you, I was answering to the original poster, who asked how to disable it. I too feel this project is suffering from neglect and I'm not sure @fredcamps here knows what's happening judging from his answers here.

**Comment by fredcamps** [comment]
@wyuenho no worries, I invited you to have access to this repository, maybe you can improve this better than me

**Comment by wyuenho** [comment]
Thanks. I'm not sure how much time I can dedicate to this project as I'm slowly moving over to VSCode these days.

**Comment by fredcamps** [comment]
@wyuenho no problem, do it when you can
